# 一般情報
title: Noraworld Developers Blog
description: >-
  日々の開発や趣味プログラミングで得た技術的な知見を共有するブログです
url: "https://noraworld.github.io"
baseurl: "/devlog/"

# プロフィール情報
username: noraworld
profile: >-
  Ruby / Rails / Shell Script / macOS / Ubuntu / Raspberry Pi / Network / Security
profile_icon: "assets/img/profile.png"
twitter_username: _noraworld
github_username: noraworld

# サイトの設定
theme: minima
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
plugins:
  - jekyll-feed
  - jemoji
google_analytics: "G-7VS1W4MH23"
google_adsense: "ca-pub-6761843998035165"

# 除外ファイルリスト
## 上の 10 個はデフォルトで除外されるらしいが念のため
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - books/
  - .gitignore
  - README.md
  - mapping.txt
  - package.json
  - package-lock.json
  - .ruby-version
  - .rubocop.yml
  - CNAME
  - articles/
  - bin/

# GitHub Pages で公開するための設定
collections:
  articles:
    output: true
    permalink: /:path
