# 一般情報
title: Noraworld Developers Blog
description: >-
  日々の開発や趣味プログラミングで得た技術的な知見を共有するブログです
url: "https://noraworld.github.io"
baseurl: "/devlog/"

# プロフィール情報
username: noraworld
profile: >-
  Ruby / Rails / Shell Script / macOS / Ubuntu / Raspberry Pi / Network / Security
profile_icon: "assets/img/profile.png"
github_username: noraworld
twitter_username: _noraworld

# サイトの設定
## kramdown はいろいろと問題がある
##
##   * リンク内の縦線がテーブルとして解釈される
##   * ヘッドラインとテーブルの間に空行を入れないとテーブルがパースされない
##   * <details> 内でマークダウンが使えない
##   * 裸の URL がリンクにならない
##
## CommonMarkGhPages はバグっていて使えない
##
##   markdown: CommonMarkGhPages
##   plugins:
##     - jekyll-commonmark-ghpages
##
## CommonMark だけでもチェックリスト ("* [x] foo") が使えない程度なので問題なし
##
theme: minima
markdown: CommonMark
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tasklist"]
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-commonmark
google_analytics: "G-7VS1W4MH23"
google_adsense: "ca-pub-6761843998035165"

# 除外ファイルリスト
## 上の 10 個はデフォルトで除外されるらしいが念のため
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - books/
  - .gitignore
  - README.md
  - mapping.txt
  - package.json
  - package-lock.json
  - .ruby-version
  - .rubocop.yml
  - CNAME
  - articles/
  - bin/
  - jekyll-build-pages

# GitHub Pages で公開するための設定
collections:
  articles:
    output: true
    permalink: /ja/:path

# 記事内では "{{ foo }}" を Liquid のシンタックスとして解釈しないようにする (Jekyll 4.0 以降で利用可能)
defaults:
  - scope:
      type: articles
    values:
      render_with_liquid: false
